### ISSUE TITLE
option to execute dart_emulators w/o unistalling present app!

### ISSUE THREAD

**Issue by a43mrk** [tim-smart/dart_emulators#12]
I couldnt find any option to start dart_emulators without he uninstalling the app; I'm in this need because some popup like notification authorization or login that pass through 2fa process really cut the integration test process and left some part for human interaction :( I really need that the screenshots to be done at the app with already logged state(resume the last state).
is there some option to switch on/off the uninstall process before finishing on integration test?

**Comment by tim-smart** [comment]
This is a limitation of flutter driver.

It is also not recommended as your tests cannot be reproduced easily.
