### ISSUE TITLE
Emulators.build() crashed integration test

### ISSUE THREAD

**Issue by Klabauterman** [tim-smart/dart_emulators#15]
I have tried to modify the demo app to use the integration_test framework instead of the deprecated flutter_driver. The problem is that calling Emulators.build() directly crashed the test, so there is no way of making screenshots. Any ideas how to solve it?

package:test_core/src/runner/plugin/platform_helpers.dart 115:19  deserializeSuite.<fn>
dart:async/zone.dart 1383:47                                      _rootRun
dart:async/zone.dart 1293:19                                      _CustomZone.run
dart:async/zone.dart 1201:7                                       _CustomZone.runGuarded
dart:async/stream_impl.dart 392:13                                _BufferingStreamSubscription._sendDone.sendDone
dart:async/stream_impl.dart 402:7                                 _BufferingStreamSubscription._sendDone
dart:async/stream_impl.dart 291:7                                 _BufferingStreamSubscription._close
dart:async/stream_controller.dart 782:19                          _SyncStreamControllerDispatch._sendDone
dart:async/stream_controller.dart 637:7                           _StreamController._closeUnchecked
dart:async/stream_controller.dart 630:5                           _StreamController.close
package:stream_channel/src/guarantee_channel.dart 55:31           new GuaranteeChannel.<fn>.<fn>
dart:async/zone.dart 1383:47                                      _rootRun
dart:async/zone.dart 1293:19                                      _CustomZone.run
dart:async/zone.dart 1201:7                                       _CustomZone.runGuarded
dart:async/stream_impl.dart 392:13                                _BufferingStreamSubscription._sendDone.sendDone
dart:async/stream_impl.dart 402:7                                 _BufferingStreamSubscription._sendDone
dart:async/stream_impl.dart 291:7                                 _BufferingStreamSubscription._close
dart:async/stream_controller.dart 782:19                          _SyncStreamControllerDispatch._sendDone
dart:async/stream_controller.dart 637:7                           _StreamController._closeUnchecked
dart:async/stream_controller.dart 630:5                           _StreamController.close
dart:async/stream_controller.dart 874:29                          _StreamSinkWrapper.close
package:stream_channel/src/guarantee_channel.dart 188:38          _GuaranteeSink.close
package:stream_channel/src/multi_channel.dart 241:29              _MultiChannel._closeInnerChannel
dart:async/zone.dart 1383:47                                      _rootRun
dart:async/zone.dart 1293:19                                      _CustomZone.run
dart:async/zone.dart 1201:7                                       _CustomZone.runGuarded
dart:async/stream_impl.dart 392:13                                _BufferingStreamSubscription._sendDone.sendDone
dart:async/stream_impl.dart 402:7                                 _BufferingStreamSubscription._sendDone
dart:async/stream_impl.dart 291:7                                 _BufferingStreamSubscription._close
dart:async/stream_controller.dart 782:19                          _SyncStreamControllerDispatch._sendDone
dart:async/stream_controller.dart 637:7                           _StreamController._closeUnchecked
dart:async/stream_controller.dart 630:5                           _StreamController.close
package:stream_channel/src/guarantee_channel.dart 55:31           new GuaranteeChannel.<fn>.<fn>
dart:async/zone.dart 1383:47                                      _rootRun
dart:async/zone.dart 1293:19                                      _CustomZone.run
dart:async/zone.dart 1201:7                                       _CustomZone.runGuarded
dart:async/stream_impl.dart 392:13                                _BufferingStreamSubscription._sendDone.sendDone
dart:async/stream_impl.dart 402:7                                 _BufferingStreamSubscription._sendDone
dart:async/stream_impl.dart 534:14                                _DelayedDone.perform
dart:async/stream_impl.dart 620:11                                _PendingEvents.handleNext
dart:async/stream_impl.dart 591:7                                 _PendingEvents.schedule.<fn>
dart:async/zone.dart 1383:47                                      _rootRun
dart:async/zone.dart 1293:19                                      _CustomZone.run
dart:async/zone.dart 1201:7                                       _CustomZone.runGuarded
dart:async/zone.dart 1241:23                                      _CustomZone.bindCallbackGuarded.<fn>
dart:async/zone.dart 1391:13                                      _rootRun
dart:async/zone.dart 1293:19                                      _CustomZone.run
dart:async/zone.dart 1201:7                                       _CustomZone.runGuarded
dart:async/zone.dart 1241:23                                      _CustomZone.bindCallbackGuarded.<fn>
dart:async/schedule_microtask.dart 40:21                          _microtaskLoop
dart:async/schedule_microtask.dart 49:5                           _startMicrotaskLoop
dart:isolate-patch/isolate_patch.dart 122:13                      _runPendingImmediateCallback
dart:isolate-patch/isolate_patch.dart 193:5                       _RawReceivePortImpl._handleMessage

Failed to load ".../flutter-emulators-screenshots-demo-main/integration_test/main_test.dart": Connection closed before test suite loaded.

**Comment by Klabauterman** [comment]
Maybe this issue is not so important, since there seems to be a lot of issues around making screenshots with the integration_test package: https://github.com/flutter/flutter/issues/92381

**Comment by tim-smart** [comment]
Unfortunately I'm not aware of a way to use integration_test for screenshots, as there is no way to communicate with the host.

**Comment by Klabauterman** [comment]
I am getting it now. I thought I could write everything in one file with the integration_test like it is in the documentation of the framework. But the problem with that is that the code then runs on the device where it has no access to command line tools and that is the reason why I cannot just call `Emulators.build()`.

I would need to split the code into driver and target, but then there is no way to communicate between driver and target. One could use the `integrationDriver` function from `integration_test_extended` that has a screenshot callback, instead of the approach from your demo app, but there is no point in it, since it uses flutter_driver anyways to do the communication and there are even some bugs in it https://github.com/flutter/flutter/issues/92381

I'll now use your demo app as a starting point, thanks for the great work @tim-smart
