### ISSUE TITLE
emu.forEach hangs waiting for Android emulators

### ISSUE THREAD

**Issue by Enrico204** [tim-smart/dart_emulators#4]
In my Linux installation (with Android Studio, `flutter doctor` ok, no issues with `flutter run` or emulators in general) `emu.forEach` hangs waiting for Android emulators. After 3 minutes, the timeout kicks in:

```
$ dart tools/screenshots.dart 
Shutdown all emulators
Creating Nexus_5X emulator
Launching screenshots
Unhandled exception:
TimeoutException after 0:03:00.000000: Future not completed
```

I tried to switch image for Nexus_5X, with no luck:
* `system-images;android-30;google_apis;x86_64`
* `system-images;android-30;google_apis;x86`
* `system-images;android-30;google_apis_playstore;x86`

If i issue `flutter run` with the emulator running, I can use/debug the app normally. `flutter devices` also shows the emulator ok:

```
$ flutter devices
2 connected devices:

sdk gphone x86 64 arm64 (mobile) • emulator-5554 • android-x64    • Android 11 (API 30) (emulator)
Chrome (web)                     • chrome        • web-javascript • Chromium 90.0.4430.212 built on Debian 10.9, running on Debian 10.11
```

I tested the code of the demo project (https://github.com/tim-smart/flutter-emulators-screenshots-demo) as well, again with no luck.

Maybe related to #3 

Any idea?

**Comment by Enrico204** [comment]
I just discovered that `updateDeviceName` crashes if the output of the `adb` command is empty, due to index error (`parts[1]` doesn't exists, as `out == ""`).

I'm still investigating why `adb` output is empty

**Comment by tim-smart** [comment]
What is the output of:

```emulator -list-avds```

Then with one of the device IDs, run:

```adb -s <device-id> emu avd name```

**Comment by Enrico204** [comment]
AVD list:
```
$ emulator -list-avds
Nexus_5X
android10
```

While `adb -s emulator-5554 emu avd name` is empty. The device ID is correct (`Nexus_5X` is currently running):

```
$ adb devices
List of devices attached
emulator-5554   device
```

If I use telnet, I can get the correct name:
```
$ telnet localhost 5554
Trying ::1...
Connected to localhost.
Escape character is '^]'.
Android Console: type 'help' for a list of commands
OK
avd name
Nexus_5X
OK
^]
telnet> quit
Connection closed.
```

**Comment by tim-smart** [comment]
Does this output anything?

```adb -s Nexus_5X emu avd name```

**Comment by Enrico204** [comment]
> Does this output anything?
> 
> `adb -s Nexus_5X emu avd name`

Empty (no output). However, the exit code for this command is `1` (while `adb -s emulator-5554 emu avd name` has zero as exit code).

**Comment by Enrico204** [comment]
Note that if I issue `adb -s emulator-5554 emu kill` the emulator terminates, so commands are sent but there is no output at all. It seems a bug in `adb`. I'm trying to reinstall my Android SDK.

**Comment by Enrico204** [comment]
I found the issue (and solved!). It's definitely a bug in `adb`. Here a summary:

* if the emulator control interface is protected by a token, it's stored in `~/.emulator_console_auth_token`. If the file is empty or it doesn't exists, no authentication is required
* `adb emu <command>` connects to the emulator control interface (via Telnet, usually `localhost:5554`), wait for token authentication request, sends the token and then sends the `<command>`. The output of the command is relayed to `stdout`
* **however** (this is the bug), when the `~/.emulator_console_auth_token` exists and empty, `adb` skips the authentication (as planned) but fails silently (exit code as zero and no output) somehow messing with the protocol itself (I suspect a dangling newline or something).

**Fix**: I just removed `~/.emulator_console_auth_token` (it's re-created after the next emulator run) and now everything is back to normal.

I think that it will be useful to add a line in the `README.md` and print a error message when `adb -s <device> emu avd name` output is empty inside `updateDeviceName` (something like: *adb emu output is empty, please remove ~/.emulator_console_auth_token if it's empty*)

**Comment by tim-smart** [comment]
Great that you found a solution!

For the time being I'll just handle bad output properly in `updateDeviceName`.

If you want to add a FAQ's section to the README, I can review a PR.

**Comment by chadacious** [comment]
Hmm, I'm experiencing no return on the `adb -s {name} emu avd name` but my `~/.emulator_console_auth_token` is not empty (although I tried deleting it anyway). Where there any other thoughts on this?

**Comment by chadacious** [comment]
> Hmm, I'm experiencing no return on the `adb -s {name} emu avd name` but my `~/.emulator_console_auth_token` is not empty (although I tried deleting it anyway). Where there any other thoughts on this?

nvm I'm an idiot. I didn't have my emulators running first. Duh.
