### ISSUE TITLE
timeout after 3 minutes when running emu.shutdownAll

### ISSUE THREAD

**Issue by speaking-in-code** [tim-smart/dart_emulators#6]
I'm testing out the dart_emulators package using flutter-emulators-screenshots-demo. The unmodified demo fails after 3 minutes with the following log:

```
$ dart tools/screenshots.dart 
Unhandled exception:
Error waiting for device: TimeoutException after 0:03:00.000000: Future not completed
#0      toFuture.<anonymous closure> (package:fpdt/task_either.dart:23:14)
#1      Left._fold (package:fpdt/either.dart:408:13)
#2      fold.<anonymous closure> (package:fpdt/either.dart:35:24)
<asynchronous suspension>
#3      Stream.asyncMap.<anonymous closure>.add (dart:async/stream.dart)
<asynchronous suspension>
```

Flutter doctor shows no issues:
```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-x64, locale
    en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version
    31.0.0-rc2)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.2)
[✓] IntelliJ IDEA Community Edition (version 2017.2.2)
[✓] Connected device (2 available)

• No issues found!
```

I am able to start Android and iOS simulators manually with no problems.

**Comment by tim-smart** [comment]
What is the output of `flutter devices`?

**Comment by speaking-in-code** [comment]
The root cause turned out to be that the emulator process had exited a few seconds after starting up. flutter devices was (correctly) showing no emulator was available.

**Comment by melodysdreamj** [comment]
same issue. in my case, when I only use fvm, does not work. when I download flutter sdk and set path in zshrc, everything work fine.

**Comment by tim-smart** [comment]
This is actually an issue with the `boot` + `waitUntilRunning` operation.

Current we are using `emulator -avd $id` to boot the device, if that command doesn't work manually then I can look into it further.
